### ISSUE TITLE
iOS 무통장입금 기능에서 옵션선택 이후 완료 버튼을 찾을 수 없습니다.

### ISSUE THREAD

**Issue by MartianLee** [iamport/iamport-capacitor#18]
안녕하세요~ 이번에 저희가 무통장입금 기능을 도입하게 되어서 테스트를 하던 중 iOS에서 옵션선택 이후 완료 버튼을 찾을 수 없는 문제를 발견하였습니다. 안드로이드에서는 괜찮은데 iOS에서만 그렇네요.

입금은행 옵션, 현금영수증 발행 예 아니오 선택 이후 옵션 창을 내릴 수 없어서 최하단의 '다음' 버튼을 누를 수가 없습니다.

확인 부탁드립니다!

![Image from iOS](https://user-images.githubusercontent.com/1390368/111556356-b5054900-87cd-11eb-80a1-f6cd62680424.png)

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

해당 이슈는 애초에 IOS 환경에서 드롭다운 선택시 나타나는 메뉴 상단에 Done 버튼이 없어서 발생하고 있습니다.
IOS 환경(모바일 웹 또는 웹뷰)에서는 드롭다운 값 변경시 자동으로 메뉴가 사라지지 않고 명시적으로 Done 버튼을 눌러야지만 사라지는데,
캐패시터(코르도바)의 키보드 기본 옵션 값이 해당 버튼이 보이지 않도록 설정되어 있습니다.

[참고 링크]
- [BUG - No done button for select tag in IOS](https://stackoverflow.com/questions/31839925/bug-no-done-button-for-select-tag-in-ios)
- [Unavailable native “done” button for hide keyboard in iOS keyboard
](https://forum.ionicframework.com/t/unavailable-native-done-button-for-hide-keyboard-in-ios-keyboard/27290)

따라서 번거로우시겠지만 고객님의 앱에서 직접 해당 옵션을 설정해주셔야 합니다.
아래는 리액트 - 캐패시터 앱에서 예시 코드입니다.

```javascript
import { Plugins } from '@capacitor/core';

const { Keyboard } = Plugins;

const Payment: React.FC = () =>  {
  useEffect(() =>  {
    // when component did mounted
    **Keyboard.setAccessoryBarVisible({ isVisible: true });**
  }, []);
}

export default Payment;
```

이용에 참고 부탁드립니다.
감사합니다.

**Comment by MartianLee** [comment]
설정 이후에 완료 버튼이 뜨는 것을 확인하였습니다.
감사합니다 🙏
