### ISSUE TITLE
capacitor 3 버전 지원부탁드립니다

### ISSUE THREAD

**Issue by bdhwan** [iamport/iamport-capacitor#42]
capacitor 3 버전 지원부탁드립니다

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

작업해주신 커밋을 참조하여 capacitor v3 를 지원하는 v1.0.0 을 배포하였습니다.

사용중 문제가 있다면 이슈 오픈 해주시기 바랍니다.

감사합니다.

**Comment by bdhwan** [comment]
감사합니다!

2021년 11월 8일 (월) 오후 8:36, BingBong ***@***.***>님이 작성:
