### ISSUE TITLE
백버튼 버그

### ISSUE THREAD

**Issue by pjc0247** [iamport/iamport-capacitor#53]
https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading
https://stackoverflow.com/a/69044230/3352855

안드로이드 가이드대로 설정하면 백버튼을 누르면 앱이 무조건 종료되는 버그가 생깁니다.

ionic 최신 버전의 가이드대로 iamport 가이드도 수정되어야 할 것 같습니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

https://github.com/iamport/iamport-capacitor/blob/06917435cc2fdd741ce6cd8ff5e30b71bf95917f/example/android/app/src/main/java/io/ionic/starter/MainActivity.java#L1-L6

맞습니다. 예제 앱에서는 위와 같이 이미 ionic 가이드대로 처리하고 있습니다만,

본 repo 의 안드로이드 가이드에는 레거시가 남아있습니다.

해당 부분 검토 후 수정해놓도록 하겠습니다.

리포팅에 감사드립니다.

**Comment by kjh5833** [comment]
가이드 내용 추가하였으므로 이슈 닫도록 하겠습니다.
